export {HomePage} from './Home'
export {AuthPage} from './Auth'
export {AboutPage} from './About'
export {ContactPage} from './Contact'
export {ProductsPage, ProductPage} from './Products'
export {NotFound} from './NotFound'